Repository 2-sc/StudyMate-Front-Client, pull requests merged in 2022-10, with the labels that each got.

#7 :sparkles::lipstick: (feature/halam/#6) Box 컴포넌트 생성
  studymate/src/components/common/Box.jsx
Labels: ✨ sparkles, :lipstick: lipstick

#13 :sparkles::lipstick: (feature/halam/#11): Calendar 컴포넌트 퍼블리싱
  studymate/package-lock.json
  studymate/package.json
  studymate/src/components/calendar/Calendar.jsx
  studymate/src/components/calendar/day-picker-customize.css
Labels: ✨ sparkles, :package: package, :lipstick: lipstick

#15 feature/halam/#14: signup 페이지 퍼블리싱
  studymate/public/video/video.mp4
  studymate/src/App.jsx
  studymate/src/pages/signup/Signup.jsx
Labels: ✨ sparkles, :lipstick: lipstick

#19 :bug: (fix/halam/#18): netlify 배포 오류 해결을 위해 리다이렉트 경로 설정
  studymate/public/_redirects
Labels: :bug: bug, :rocket: rocket

#17 ✨🎨💄 (feature/halam/#16): 기존 Sign 페이지를 컴포넌트로 분리 후 Login 페이지까지 퍼블리싱 완료
  studymate/src/components/sign/Inputs.jsx
  studymate/src/components/sign/Sign.jsx
  studymate/src/pages/login/Login.jsx
  studymate/src/pages/signup/Signup.jsx
Labels: ✨ sparkles, :art: art, :lipstick: lipstick

#28 :sparkles::lipstick:(feature/halam/#27): 파이그래프 컴포넌트 생성
  studymate/package-lock.json
  studymate/package.json
  studymate/src/components/graph/Graph.jsx
  studymate/src/components/graph/PieGraph.jsx
  studymate/src/components/graph/dummyData.js
Labels: 🎉 start, :lipstick: lipstick

#31 Planner 다짐 UI 구현
  studymate/package-lock.json
  studymate/src/pages/planner/Planner.jsx
  studymate/src/pages/planner/dazim/Dazim.jsx
  studymate/src/styles/layout/Items.jsx
  studymate/src/styles/layout/SideBar.jsx
Labels: :lipstick: lipstick

#34 Todolist UI 구현
  studymate/package-lock.json
  studymate/package.json
  studymate/src/assets/checkbox.svg
  studymate/src/pages/planner/Planner.jsx
  studymate/src/pages/planner/todolist/TodoInsert.jsx
  studymate/src/pages/planner/todolist/TodoList.jsx
  studymate/src/pages/planner/todolist/TodoListItem.jsx
  studymate/src/styles/layout/Layout.jsx
Labels: :lipstick: lipstick

#36 로그 페이지에서 달력 컴포넌트와 그래프 컴포넌트 사용
  studymate/src/components/graph/Graph.jsx
  studymate/src/components/graph/TimeLineGraph.jsx
  studymate/src/pages/log/Log.jsx
Labels: :construction: construction, :lipstick: lipstick

#43 프로필 편집 퍼블리싱
  studymate/src/App.jsx
  studymate/src/pages/editprofile/EditProfile.jsx
  studymate/src/pages/editprofile/InfoContainer.jsx
  studymate/src/styles/layout/SideBar.jsx
Labels: :lipstick: lipstick

#44 stopwatch UI 및 카테고리 UI (모달) 구현
  studymate/src/pages/stopwatch/StopWatch.jsx
  studymate/src/pages/stopwatch/category/Category.jsx
  studymate/src/pages/stopwatch/category/CategoryInsert.jsx
  studymate/src/pages/stopwatch/category/CategoryListItem.jsx
  studymate/src/pages/stopwatch/category/ModalCategory.jsx
  studymate/src/pages/stopwatch/category/ModalFrame.jsx
Labels: :lipstick: lipstick

#45 스케줄 UI 구현 완료
  studymate/src/pages/planner/Planner.jsx
  studymate/src/pages/planner/schedule/Schedule.jsx
  studymate/src/pages/planner/schedule/ScheduleListItem.jsx
  studymate/src/pages/planner/schedule/SchedulePlus.jsx
  studymate/src/pages/planner/todolist/TodoListItem.jsx
Labels: :lipstick: lipstick

#51 :sparkles:(feature/halam/#50): d-day 달력모달 구현
  studymate/public/index.html
  studymate/src/components/calendar/Calendar.jsx
  studymate/src/components/calendar/Modal.jsx
  studymate/src/pages/editprofile/InfoContainer.jsx
Labels: ✨ sparkles, :lipstick: lipstick
